import { Press_Start_2P, IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import NavbarMain from '@/components/navbar-main';
import Footer from '@/components/footer';

const pressStart = Press_Start_2P({
    variable: '--font-press-start',
    weight: ['400'],
    subsets: ['latin'],
});

const plexMono = IBM_Plex_Mono({
    variable: '--font-plex-mono',
    weight: ['100', '200', '300', '400', '500', '600', '700'],
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang='en'
            className={`${pressStart.variable} ${plexMono.variable} h-full antialiased`}
        >
            <body className='font-plexMono bg-base-200 text-base-content flex min-h-full flex-col'>
                <NavbarMain />
                <main className='container mx-auto grow px-4 py-6'>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
